# Generated by Django 4.1.5 on 2023-01-05 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('rest_url', models.URLField(verbose_name='REST URL')),
                ('login_id', models.CharField(max_length=32, verbose_name='Login ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('soap_username', models.CharField(max_length=32, verbose_name='Username')),
                ('soap_password', models.CharField(max_length=32, verbose_name='Password')),
                ('access_token', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Access Token')),
                ('last_request', models.DateTimeField(null=True, verbose_name='Last Request')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('session_id', models.BigIntegerField(editable=False, unique=True, verbose_name='Session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.account', verbose_name='Account')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('response', models.JSONField(editable=False, verbose_name='Response')),
                ('payload', models.JSONField(editable=False, verbose_name='Request')),
                ('method', models.CharField(max_length=32, verbose_name='Method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.session', verbose_name='Session')),
            ],
        ),
    ]
